"""add google oauth fields to user

Revision ID: 50390f608ff5
Revises: 20260731_0008
Create Date: 2026-08-14 20:55:28.380652
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '50390f608ff5'
down_revision: str | None = '20260731_0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True))
    # SQLite는 ALTER COLUMN을 지원하지 않아서(op.alter_column을 그대로 쓰면
    # "ALTER TABLE ... ALTER COLUMN ... DROP NOT NULL" 문법 오류가 남) batch
    # 모드로 감싼다. Postgres 등에서는 batch_alter_table도 그냥 평범한
    # ALTER COLUMN을 내므로 동작이 똑같다.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'hashed_password',
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'hashed_password',
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
