"""add assessment_anchors table

Revision ID: 9c492a34c88b
Revises: 20260727_0003
Create Date: 2026-07-27 20:05:03.267124
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9c492a34c88b'
down_revision: str | None = '20260727_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_anchors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.Enum('CUSTOM_INITIAL_STATE_SURVEY', 'K_BAT', name='assessmenttype'), nullable=False),
    sa.Column('target_group', sa.Enum('UNIVERSITY_STUDENT', 'JOB_SEEKER', 'EARLY_CAREER_WORKER', name='usertype'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('interpretation_scope', sa.Enum('FIXED_REFERENCE_ONLY', name='interpretationscope'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['assessment_anchors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_anchors_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_anchors_user_id'))

    op.drop_table('assessment_anchors')
    # ### end Alembic commands ###
