"""add consent_records table

Revision ID: f4c75e0aa428
Revises: fe74618fc15c
Create Date: 2026-07-29 13:40:10.647571
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f4c75e0aa428'
down_revision: str | None = 'fe74618fc15c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('consent_type', sa.Enum('HEALTH_DATA', 'EMOTION_DIARY', name='consenttype'), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'WITHDRAWN', name='consentstatus'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_user_id'))

    op.drop_table('consent_records')
    # ### end Alembic commands ###
