"""add name column to users

Revision ID: fe74618fc15c
Revises: 9c492a34c88b
Create Date: 2026-07-28 16:46:36.065987
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'fe74618fc15c'
down_revision: str | None = '9c492a34c88b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
